### ISSUE TITLE
Error in microstructure_characterization_GUI

### ISSUE THREAD

**Issue by nagda95** [NREL/MATBOX_Microstructure_analysis_toolbox#16]
Hello,
I have installed the MATBOX app in Matlab 2020b running on Windows. I am trying to Run all calculations for microstructure characterization after loading the segmented volume but I am facing this error:

**Reference to non-existent field 'filename_input'.

Error in function_microstructure_characterization_segmentedvolume (line 53)
    str = sprintf ('%s',INFO.filename_input);**

**Comment by rokiatamraz12556** [comment]
Hi. I also encountered this error today.
