### ISSUE TITLE
Error when meshing the volume with iso2mesh

### ISSUE THREAD

**Issue by nagda95** [NREL/MATBOX_Microstructure_analysis_toolbox#19]
I am trying to mesh the microstructure volume using iso2mesh option to get a Tetrahedron based unstructured mesh with mesh density control and smooth surface. However, I am unable to run the script successfully. Your time and help is highly appreciated.

I get the following error:

**creating surface and tetrahedral mesh from a multi-domain volume ...
'"cgalmesh_x86-64.exe"' is not recognized as an internal or external command, 
operable program or batch file. 
Error using cgalv2m (line 87)
output file was not found, failure was encountered when running command: \n"cgalmesh_x86-64.exe" "C:\Users\vinit\AppData\Local\Temp\iso2mesh-vinit\pre_cgalmesh.inr"**

**Comment by fussegli** [comment]
Hi, thanks for reporting your issue.
Could you answer the following questions so i can help you?
- What message do you get if you write iso2meshver in the Matlab command window ?
- How did you install Iso2mesh ?
- What is your OS ?
- What is your MATLAB version ?

**Comment by nagda95** [comment]
Hello @fussegli ,
Thank you for your response.

1. What message do you get if you write iso2meshver in the Matlab command window ?
>> iso2meshver
iso2mesh toolbox version: 1.9.5-Rev

2. How did you install Iso2mesh ?
I downloaded it from https://github.com/fangq/iso2mesh

3.What is your OS ?
64-bit operating system, x64-based processor

4.What is your MATLAB version ?
MATLAB R2020b

**Comment by nagda95** [comment]
@fussegli Hi, were you able to see this issue yourself? Do you know how it can be fixed?
Thanks.

**Comment by fussegli** [comment]
Hi,

The message you should get is:

>> iso2meshver
iso2mesh toolbox version: 1.9.5-Rev
creating surface and tetrahedral mesh from a multi-domain volume ...
Volume/Surface Mesh Generation Utility (Based on CGAL 5.0) 
(modified for iso2mesh by Qianqian Fang and Peter Varga) 
http://iso2mesh.sf.net 
 
RNG seed=1648335518 
Mesh sizes are (label=size) (1=1000)  
node number:	128112
triangles:	515342
tetrahedra:	667862
regions:	3
surface and volume meshes complete
generating tetrahedral mesh from closed surfaces ...
creating volumetric mesh from a surface mesh ...
volume mesh generation is complete

I also re-downloaded the latest Iso2mesh version from the github repo to make sure i am using the same library than you and i do not get your error. The only difference is i am working with Matlab2021b, but that should not cause any issue.

When you have added Iso2mesh to the Matlab path, did you check 'Add with sub-folders' ? 

I noticed in your error message, the temp folder is in your C\Users\ and that can create issue. Your problem may lie with the temporary folder Iso2mesh is using for writing. See http://iso2mesh.sourceforge.net/cgi-bin/index.cgi?Advanced, and try changing ISO2MESH_TEMP. Let me know if it works.

Best

**Comment by nagda95** [comment]
@fussegli I changed the output location for ISO2MESH_TEMP and it seems to be working now without any error. 
Thank you very much.

**Comment by nagda95** [comment]
@fussegli It seemed to work for the first time but it again gives the same error now. I changed the output location for ISO2MESH_TEMP but the error comes again (earlier the error was just for file 'pre_cgalmesh.inr' but now it is also for 'post_cgalmesh.mesh'):
Error using cgalv2m (line 97)
output file was not found, failure was encountered when running command: \n"cgalmesh.exe"
"C:\Users\vinit\OneDrive\Documents\MATLAB\MATBOX_Microstructure_analysis_toolbox-master\iso2mesh\iso_temp\pre_cgalmesh.inr"
"C:\Users\vinit\OneDrive\Documents\MATLAB\MATBOX_Microstructure_analysis_toolbox-master\iso2mesh\iso_temp\post_cgalmesh.mesh

**Comment by fussegli** [comment]
Hi,
-You could try to set up this variable with https://www.mathworks.com/help/matlab/ref/setenv.html so that MATLAB knows about it for each new sessions.
-Alternatively, you could hardcode it, write:
global ISO2MESH_TEMP;
ISO2MESH_TEMP = [your folder];
in src\Create_mesh_for_FEM\function_iso2mesh_from_array.m. I remember i did just this for my Ubuntu workstation when i run into this issue some times ago.
Please let me know if one of these solutions work for you.
Best

**Comment by nagda95** [comment]
@fussegli Hi, it still does not work. I get the same error again, I do not understand why.

**Comment by fussegli** [comment]
Hi Nagda, do you still have the error ?

**Comment by nagda95** [comment]
@fussegli Thank you for your concern and help. The error is fixed now. Thanks
