### ISSUE TITLE
Main menu functions return "unrecognized"

### ISSUE THREAD

**Issue by DuncanWilliamGibbons** [NREL/MATBOX_Microstructure_analysis_toolbox#20]
When clicking on any of the main menu buttons I get the following error code in Matlab R2021a:

`Unrecognized function or variable "microstructure_characterization_GUI".`

`Error in Main_menu/MicrostructurecharacterizationButton_2Pushed (line 61)
            microstructure_characterization_GUI`
 
`Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.`

**Comment by fussegli** [comment]
Hi,
This looks to me as the MATLAB path has not been updated. Did you have a look at the installation instructions in the documentation ?
Please let me know if this fix it or if you have still issues running MATBOX.
Best
-Francois

**Comment by fussegli** [comment]
Hi do you still have the problem ? Otherwise I will close the issue.

**Comment by DuncanWilliamGibbons** [comment]
Apologies, yes this fixed it. Thanks
