### ISSUE TITLE
potential bugs for generating porous structure only fill in half of the domain

### ISSUE THREAD

**Issue by GitPaean** [NREL/MATBOX_Microstructure_analysis_toolbox#22]
Hi, when I tried to generate porous structure to only fill in half of the domain, the software always trying to generate porous structure to fill almost the whole domain. 

```matlab
>> phase.volumefraction.along_3rd_axis

ans =

         0    0.4900    0.5100    1.0000
         0         0    0.5000    0.5000

>> domain_size

domain_size =

   100   100   200
```

And the resulting structure looks like 
![image](https://user-images.githubusercontent.com/6847941/171994032-d391fe4b-8e0d-4a24-baf2-aeb81e6dad6f.png)

And the inputs are very simple, it is attached here, 
[Inputs.zip](https://github.com/NREL/MATBOX_Microstructure_analysis_toolbox/files/8837404/Inputs.zip)

Any comments or suggestions? Thanks.

**Comment by fussegli** [comment]
Hi GitPaean.
Good catch! I was able to reproduce the error and I summited a fix.
Please check on your side and confirm you have no more problem so that I can close this issue.
Thanks

![Bugfix](https://user-images.githubusercontent.com/41033828/172201218-1cee35ef-37d4-47cc-b71c-b786027fc09a.png)

**Comment by GitPaean** [comment]
Hi, I am out of the office this week. Will try it by the Monday. Thanks for the fix.

**Comment by GitPaean** [comment]
I can confirm that the fix works properly. Thanks for the efforts. I am closing the issue now as it is solved.
