### ISSUE TITLE
Error using VideoWriter/writeVideo Frame must be 1720 by 720

### ISSUE THREAD

**Issue by GitPaean** [NREL/MATBOX_Microstructure_analysis_toolbox#23]
Not sure how to reproduce it, it shows up from time to time and not sure if the developers experienced the following error messages, 

It happens when using the GUI to generate some porous structure, 
```matlab
Error using VideoWriter/writeVideo
Frame must be 1720 by 720

Error in function_generate_ellipsoid_microstructure (line 555)
                        writeVideo(video_handle,stored_frame(frame_number))

Error in Microstructure_generation_stochastic/Generate_ButtonPushed (line 1383)
                [microstructure3D, current_phaseinfo, outcome] = function_generate_ellipsoid_microstructure(app.domain_size,app.phase,app.Maximum_overlapping,app.Minimum_particle_volume_conservated,~app.disable_contiguituy_check, stoping_conditions, do_verification, save_options);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error while evaluating Button PrivateButtonPushedFcn.
```

**Comment by fussegli** [comment]
This error can be reproduced if user tries to manually resize the figure being used for the video. MATLAB expects each frame of the video to have the same size.
So, until algorithm finishes do not resize figures.
I will add later a warning in the GUI so people knows about it.

**Comment by GitPaean** [comment]
> This error can be reproduced if user tries to manually resize the figure being used for the video. 

Thanks for the response. It can be true. I did not intentionally resize the figure, but it can be accidental when moving around the mouse.   But your information is very helpful, because it can be frustrating when you finished the configuration and want to get it running.

**Comment by fussegli** [comment]
I made a small commit, with among other small things, this addition:

```
try
    writeVideo(video_handle,stored_frame(frame_number))
catch ME
    if (strcmp(ME.identifier,'MATLAB:audiovideo:VideoWriter:invalidDimensions'))
        error('User has manually resized figure. Video file cannot be saved! Until algorithm finishes, please do not resize figures.')
    end
end

```
I tested it, and if I resize the figure while running the algorithm, error arises with this more meaningful text. This should be enough for other users if they meet this issue in the future.
