### ISSUE TITLE
Scaling factor with the GUI does not look it works

### ISSUE THREAD

**Issue by GitPaean** [NREL/MATBOX_Microstructure_analysis_toolbox#24]
When using the GUI, when specifying a Scaling factor of 5, with the domain size to be `100*100*100`, I am expecting to get the dimension of the generated `tif` file to be `500*500*500`.  But at the end, the size of the `Phaselabel_run_1.tif` file is always `100*100*100`. Basically, it means to me that the scaling factor did not work. 

Please correct me if I misunderstood the setup.  Thanks. 

![image](https://user-images.githubusercontent.com/6847941/174089251-7a4d67a2-f281-4064-afbc-2f81d0b35296.png)

![image](https://user-images.githubusercontent.com/6847941/174089158-db513447-9698-4db9-a4ca-e8bc17c55566.png)

**Comment by fussegli** [comment]
You need to select the adequate choice in the save tab, see joined pictures. If you want to also upscale the particle id, in addition to the phase label, there is an option in the upscale tab.
Please close the issue if it works on your side.

![Picture1](https://user-images.githubusercontent.com/41033828/174098866-6fdd3e1b-03e4-45c9-93c9-9411cc56575e.png)
![Picture3](https://user-images.githubusercontent.com/41033828/174098877-ef9e6cc5-61fb-4248-a9cd-ea960f9cc356.png)
