### ISSUE TITLE
Tiff file is not extracted when using Inputs.mat on script

### ISSUE THREAD

**Issue by MEMPANE** [NREL/MATBOX_Microstructure_analysis_toolbox#26]
When I use Inputs.mat made from previous work, the tiff file is not exported.

![image](https://user-images.githubusercontent.com/36437861/192181210-78384ae8-f01f-46da-98d3-8076c6bdeabd.png)

Practice5 folder contains files from the initial work.
Practice5_import folder contains files extracted when using Inputs.mat on Matlab script. There is no tiff file in this folder.

The source code is as follows:

clc;
clear;

Foldername = 'Practice5_import'; % Folder to save
mkdir(Foldername);
addpath(Foldername);

inputs = load('Practice5\Inputs.mat');
inputs.saveoptions.folder = strcat(Foldername, '\');
inputs.saveoptions.run_number = 1; % Number of run
inputs.saveoptions.save_progression = true; % Plot progression during generation
inputs.saveoptions.save_verification = true; % Check inputs versus outputs

[microstructure3D, phase, particle_data, outcome] = function_generate_ellipsoid_microstructure(...
    inputs.domain_size,...
    inputs.phase,...
    inputs.tolerance,...
    inputs.overlapping,...
    inputs.check_contiguity,...
    inputs.stopingconditions,...
    inputs.doverification,...
    inputs.saveoptions);

**Comment by fussegli** [comment]
Hello, please re-clone and use the function Microstructure_generation_stochastic_frominputs instead of the current syntax.
It it works, please close the issue.  Otherwise please let me know.
Best,

```
help Microstructure_generation_stochastic_frominputs
  Stochastic generation algorithm from pre-existing input file
  In all cases, you must run the Microstructure_generation_stochastic app at least once to generate an input file.
  Then, please load this file: inputs=load('<your path>\Inputs.mat');
  - Default use, no scaling: Microstructure_generation_stochastic_frominputs(inputs, run_number, savefolder,save_progression, save_verification)
    run_number = 2 % How many generation (for reproducibility)
    savefolder = <where you want to save>. Path must end with '\'.
    save_progression = true; % true of false
    save_verification = true; % true of false
  - With scaling: Microstructure_generation_stochastic_frominputs(inputs, run_number, savefolder, save_progression, save_verification, scaling_factor, scaling_parameters)
    Set run_number, savefolder,  save_progression and save_verification as done above, then:
    scaling_factor = 2 % float, >0 (>1 upscaling, <1 downscaling)
    - scaling_parameters.method = 1 % Re-create from partice information (recommended)
        - scaling_parameters.scale_diameterratio = 1 % float, >0
        - scaling_parameters.Forceseparation = false % true or false
        - scaling_parameters.distance_separation = 1 % float, >0 in voxel length (used only if Forceseparation=true)
    OR
    - scaling_parameters.method = 2 % Classic up/down scaling
        - scaling_parameters.scale_particlelabel = true; true (slow) or false (only phase label will be upscaled)
```

**Comment by MEMPANE** [comment]
Thank you for your response. However, the problem was still unsolved.

Below is my simple script. 
![image](https://user-images.githubusercontent.com/36437861/192407723-088be6fd-8de2-44fb-9751-02d019f6f62d.png)

The error message is as follows:
![image](https://user-images.githubusercontent.com/36437861/192407902-3d23e1e3-ae1f-4330-a9e2-521d0a6e9f88.png)

Probably it is related to the format of Inputs.mat ...

**Comment by fussegli** [comment]
Hello, 'undefined function' means MATLAB does not see this function in its path.  If you have not update yet the repo, please do it, and then add to path the whole MATBOX folder. Then type:
`Microstructure_generation_stochastic_frominputs(inputs, run_number, savefolder,save_progression, save_verification)`

**Comment by MEMPANE** [comment]
Hello.

Sorry for trying an outdated version. I just re-downloaded the code.

It works like a charm! Thank you for your quick help.
